apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  email_user: {{ .Values.frontend.emailUser }}
  email_pass: {{ .Values.frontend.emailPass }}
