apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mongodb
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 27017
  type: {{ .Values.service.type }}
