apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.env.port }}
          env:
            - name: MONGODB_URI
              value: "{{ .Values.env.mongodbUri }}"
            - name: SESSION_SECRET
              value: "{{ .Values.env.sessionSecret }}"
            - name: PORT
              value: "{{ .Values.env.port | quote }}"
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: email_user
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: email_pass
