# apiVersion: v1
# kind: Secret
# metadata:
#   name: app-secrets
#   namespace: {{ .Release.Namespace }}
# type: Opaque
# data:
#   email_user: {{ .Values.secret.emailUser | b64enc }}
#   email_pass: {{ .Values.secret.emailPass | b64enc }}


apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  email_user: {{ .Values.secret.emailUser | b64enc | quote }}
  email_pass: {{ .Values.secret.emailPass | b64enc | quote }}
