apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: frontend-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.env.port }}
  type: {{ .Values.service.type }}
