apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: my-app
type: Opaque
data:
  email_user: Y2hhZ2FudHl0ZWphMjUwMkBnbWFpbC5jb20=  # base64 encoded
  email_pass: eXhvcSBianVrIHJkbnQgYWx6cA==           # base64 encoded
